# Pimoroni RGB Keypad
esphome:
  name: keypad
  friendly_name: keypad

rp2040:
  board: rpipicow

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Keypad Fallback Hotspot"
    password: ""
    
spi:
  mosi_pin: GPIO19
  clk_pin: GPIO18

i2c:
  - id: bus_a   
    scan: True# Example configuration entry
tca9555:
  - id: 'TCA9555_hub'
    address: 0x20
    i2c_id: bus_a


          
binary_sensor:
  - id: button0
    name: "Button 0"
    platform: gpio
    pin:
      tca9555: TCA9555_hub
      number: 0
      inverted: True
    filters:
      - delayed_on: 10ms      
    on_press:
      then:
      - homeassistant.service:
          service: homeassistant.toggle
          data:
            entity_id: switch.jade_s_bedroom_light
  - id: button3
    name: "Button 3"
    platform: gpio
    pin:
      tca9555: TCA9555_hub
      number: 3
      inverted: True
    filters:
      - delayed_on: 10ms
    on_state_change: 
      then:
        - light.addressable_set:
            id: rgb_led
            range_from: 3
            range_to: 3
            red: 10%
            green: 0%
            blue: 0%                   
  - id: button4
    name: "Button 4"
    platform: gpio
    pin:
      tca9555: TCA9555_hub
      number: 4
      inverted: True
    filters:
      - delayed_on: 10ms      
    on_press:
      then:
      - homeassistant.service:
          service: homeassistant.toggle
          data:
            entity_id: switch.desk_light
  - id: button8
    name: "Button 8"
    platform: gpio
    pin:
      tca9555: TCA9555_hub
      number: 8
      inverted: True
    filters:
      - delayed_on: 10ms      
    on_press:
      then:
      - homeassistant.service:
          service: homeassistant.toggle
          data:
            entity_id: light.lenovo_smart_led_lightstrip
  - id: button12
    name: "Button 12"
    platform: gpio
    pin:
      tca9555: TCA9555_hub
      number: 12
      inverted: True
    filters:
      - delayed_on: 10ms      
    on_press:
      then:
      - homeassistant.service:
          service: homeassistant.toggle
          data:
            entity_id: light.lenovo_smart_led_lightstrip_1

switch:
  - platform: homeassistant
    id: b1
    entity_id: switch.jade_s_bedroom_light
    on_turn_on: 
      then:
        - light.addressable_set:
            id: rgb_led
            range_from: 0
            range_to: 0
            red: 10%
            green: 50%
            blue: 50%     
    on_turn_off: 
      then:
        - light.addressable_set:
            id: rgb_led
            range_from: 0
            range_to: 0
            red: 0%
            green: 0%
            blue: 0%     
  - platform: homeassistant
    id: b2
    entity_id: switch.desk_light
    on_turn_on: 
      then:
        - light.addressable_set:
            id: rgb_led
            range_from: 4
            range_to: 4
            red: 10%
            green: 50%
            blue: 50%     
    on_turn_off: 
      then:
        - light.addressable_set:
            id: rgb_led
            range_from: 4
            range_to: 4
            red: 0%
            green: 0%
            blue: 0%     
  - platform: homeassistant
    id: b3
    entity_id: light.lenovo_smart_led_lightstrip
    on_turn_on: 
      then:
        - light.addressable_set:
            id: rgb_led
            range_from: 8
            range_to: 8
            red: 10%
            green: 50%
            blue: 50%     
    on_turn_off: 
      then:
        - light.addressable_set:
            id: rgb_led
            range_from: 8
            range_to: 8
            red: 0%
            green: 0%
            blue: 0%               
  - platform: homeassistant
    id: b4
    entity_id: light.lenovo_smart_led_lightstrip_1
    on_turn_on: 
      then:
        - light.addressable_set:
            id: rgb_led
            range_from: 12
            range_to: 12
            red: 10%
            green: 50%
            blue: 50%     
    on_turn_off: 
      then:
        - light.addressable_set:
            id: rgb_led
            range_from: 12
            range_to: 12
            red: 0%
            green: 0%
            blue: 0%               
light:
  - platform: spi_led_strip
    cs_pin: GPIO17
    num_leds: 16
    id: rgb_led
    name: "RGB LED Strip"
    data_rate: 20000000.0
    on_turn_on: 
      - logger.log: "Lights Turned On"          
    on_turn_off: 
      - logger.log: "Lights Turned Off"

