binary_sensor:
  - platform: status
    name: "Node Status"
    id: system_status
    icon: mdi:lan-connect

sensor:
  - platform: internal_temperature
    name: "ESP32 Internal Temperature"
    update_interval: 60s

button:
  - platform: restart
    name: "Restart"
