binary_sensor:
  - platform: status
    name: "Node Status"
    id: system_status
    icon: mdi:lan-connect

sensor:
  - platform: internal_temperature
    name: "Core Temperature"

button:
  - platform: restart
    name: "Restart"
