sensor:
  - platform: internal_temperature
    name: "Core Temperature"

binary_sensor:
  - platform: status
    name: "Node Status"
    id: system_status
    icon: mdi:lan-connect

status_led:
  pin:
    number: LED

button:
  - platform: restart
    name: "Restart"

debug:
  update_interval: 30s

# Expose the Free memory metric in Home Assistant
sensor:
  - platform: debug
    free:
      name: "Free Heap"
